### ISSUE TITLE
v4.0.0 string index out of range while analyzing

### ISSUE THREAD

**Issue by hsAssassin** [TechGeek01/BackDrop#24]
**Describe the bug**
While analyzing, the console prints error message and analyzation never completes.

**Environment**
- **Operating system:** Windows Server 2022 Standard
- **Program version:** 4.0.0

**To Reproduce**
The console prints the following error after analyzation starts. 

**Screenshots**
![image](https://github.com/TechGeek01/BackDrop/assets/46046667/3e094f6e-ec41-49af-8f5a-0508c627816c)

**Additional context**
Version 3.3.0 is working and does not have this bug backing up the same files.  I have a large repo to be backed up (about 8 tb).

**Comment by TechGeek01** [comment]
Pretty sure this error, or one similar to it, was fixed in commit 8500380. There were some issues I fixed with certain source/destination mode combos causing this error.

I don't have a compiled build yet, but if you're feeling adventurous enough, if you'd like to install Python and the package requirements, and give the latest commit a try.

**Comment by TechGeek01** [comment]
Should be fixed in v4.0.1
